-- ==============================================================================
-- PLAZA MANAGEMENT SYSTEM - COMPLETE ALL-IN-ONE DATABASE MIGRATION
-- Run this script in your Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. PLAZAS & UNITS (Phase 1)
CREATE TABLE IF NOT EXISTS plazas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  total_shops INTEGER DEFAULT 14,
  total_rooms INTEGER DEFAULT 8,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  unit_number TEXT NOT NULL,
  unit_name TEXT NOT NULL,
  unit_type TEXT NOT NULL CHECK (unit_type IN ('SHOP', 'ROOM')),
  floor TEXT NOT NULL,
  default_monthly_rent NUMERIC NOT NULL DEFAULT 0,
  default_security_amount NUMERIC NOT NULL DEFAULT 0,
  default_rent_due_day INTEGER NOT NULL DEFAULT 5,
  status TEXT NOT NULL DEFAULT 'VACANT' CHECK (status IN ('OCCUPIED', 'VACANT', 'INACTIVE')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_plaza_unit UNIQUE (plaza_id, unit_number)
);

CREATE INDEX IF NOT EXISTS idx_units_plaza_id ON units(plaza_id);
CREATE INDEX IF NOT EXISTS idx_units_type ON units(unit_type);
CREATE INDEX IF NOT EXISTS idx_units_status ON units(status);

-- 2. TENANTS & LEASES (Phase 2)
CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT,
  cnic TEXT,
  emergency_contact TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'VACATED', 'INACTIVE')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  monthly_rent NUMERIC NOT NULL DEFAULT 0,
  rent_due_day INTEGER NOT NULL DEFAULT 5,
  security_amount NUMERIC NOT NULL DEFAULT 0,
  security_paid NUMERIC NOT NULL DEFAULT 0,
  security_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (security_status IN ('PAID', 'PARTIAL', 'UNPAID')),
  move_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  lease_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  lease_end_date DATE,
  annual_increase_pct NUMERIC DEFAULT 10,
  last_escalation_date DATE,
  next_escalation_date DATE,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ENDED', 'TERMINATED')),
  ended_at TIMESTAMPTZ,
  vacate_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);
CREATE INDEX IF NOT EXISTS idx_leases_tenant_id ON leases(tenant_id);
CREATE INDEX IF NOT EXISTS idx_leases_unit_id ON leases(unit_id);
CREATE INDEX IF NOT EXISTS idx_leases_status ON leases(status);

-- 3. ELECTRICITY CONNECTION UNIT MAPPINGS (Phase 3)
CREATE TABLE IF NOT EXISTS connection_unit_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id BIGINT REFERENCES connections(id) ON DELETE CASCADE NOT NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  split_type TEXT NOT NULL DEFAULT 'EQUAL' CHECK (split_type IN ('EQUAL', 'PERCENTAGE', 'FIXED_AMOUNT')),
  split_value NUMERIC NOT NULL DEFAULT 100,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_conn_unit UNIQUE (connection_id, unit_id)
);

CREATE INDEX IF NOT EXISTS idx_conn_unit_conn_id ON connection_unit_mappings(connection_id);
CREATE INDEX IF NOT EXISTS idx_conn_unit_unit_id ON connection_unit_mappings(unit_id);

-- 4. MONTHLY TENANT ACCOUNTS (Phase 4)
CREATE TABLE IF NOT EXISTS tenant_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  lease_id BIGINT REFERENCES leases(id) ON DELETE SET NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  billing_month DATE NOT NULL,
  rent_amount NUMERIC NOT NULL DEFAULT 0,
  rent_due_date DATE,
  rent_paid NUMERIC NOT NULL DEFAULT 0,
  rent_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (rent_status IN ('PAID', 'PARTIAL', 'UNPAID', 'OVERDUE')),
  electricity_amount NUMERIC DEFAULT NULL,
  electricity_due_date DATE DEFAULT NULL,
  electricity_paid NUMERIC NOT NULL DEFAULT 0,
  electricity_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (electricity_status IN ('PAID', 'PARTIAL', 'UNPAID', 'OVERDUE')),
  has_electricity_bill BOOLEAN DEFAULT false,
  electricity_is_shared BOOLEAN DEFAULT false,
  maintenance_amount NUMERIC NOT NULL DEFAULT 0,
  other_charges NUMERIC NOT NULL DEFAULT 0,
  previous_balance NUMERIC NOT NULL DEFAULT 0,
  total_payable NUMERIC NOT NULL DEFAULT 0,
  total_paid NUMERIC NOT NULL DEFAULT 0,
  remaining_balance NUMERIC NOT NULL DEFAULT 0,
  overall_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (overall_status IN ('PAID', 'PARTIAL', 'UNPAID', 'OVERDUE')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_tenant_account_month UNIQUE (tenant_id, billing_month),
  CONSTRAINT unique_unit_account_month UNIQUE (unit_id, billing_month)
);

CREATE INDEX IF NOT EXISTS idx_tenant_accounts_tenant_id ON tenant_accounts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_accounts_unit_id ON tenant_accounts(unit_id);
CREATE INDEX IF NOT EXISTS idx_tenant_accounts_billing_month ON tenant_accounts(billing_month);

-- 5. PAYMENT TRANSACTIONS (Phase 5)
ALTER TABLE payments ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS lease_id BIGINT REFERENCES leases(id) ON DELETE SET NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_type TEXT NOT NULL DEFAULT 'RENT' CHECK (payment_type IN ('RENT', 'ELECTRICITY', 'SECURITY', 'MAINTENANCE', 'OTHER'));

CREATE INDEX IF NOT EXISTS idx_payments_tenant_id ON payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_payments_type ON payments(payment_type);

-- 6. COMPLAINTS & REPAIR EXPENSES (Phase 6 & 7)
CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE SET NULL,
  complaint_number TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Electrical', 'Wall / Paint', 'Roof', 'Water / Plumbing', 'Door / Lock', 'Flooring', 'AC', 'Washroom', 'Leakage', 'Structural', 'Other')),
  title TEXT NOT NULL,
  description TEXT,
  photo_attachment TEXT,
  complaint_date DATE NOT NULL DEFAULT CURRENT_DATE,
  priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
  assigned_to TEXT,
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_complaints_unit_id ON complaints(unit_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_priority ON complaints(priority);

CREATE TABLE IF NOT EXISTS complaint_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE NOT NULL,
  expense_type TEXT NOT NULL DEFAULT 'MATERIAL' CHECK (expense_type IN ('MATERIAL', 'LABOUR', 'OTHER')),
  description TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  vendor_name TEXT,
  payment_method TEXT DEFAULT 'Cash',
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_complaint_expenses_complaint_id ON complaint_expenses(complaint_id);

-- 7. GENERAL PLAZA EXPENSES (Phase 8)
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN (
    'Generator Fuel / Maintenance',
    'Security Guard Salary',
    'Janitorial / Sweeper / Cleaning',
    'Common Area Utilities',
    'Waste Disposal',
    'Government Taxes / Property Tax',
    'Building Maintenance / Repairs',
    'Legal / Admin',
    'Other'
  )),
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT NOT NULL DEFAULT 'Cash' CHECK (payment_method IN ('Cash', 'Bank Transfer', 'Online', 'Cheque', 'Other')),
  paid_to TEXT,
  receipt_voucher_no TEXT,
  is_recurring BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);

-- ==============================================================================
-- ENABLE ROW LEVEL SECURITY & PUBLIC ACCESS POLICIES
-- ==============================================================================
ALTER TABLE plazas ENABLE ROW LEVEL SECURITY;
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE connection_unit_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

DO $$ 
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY[
    'plazas', 'units', 'tenants', 'leases', 'connection_unit_mappings', 
    'tenant_accounts', 'complaints', 'complaint_expenses', 'expenses'
  ]) LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Public select on %I" ON %I;', tbl, tbl);
    EXECUTE format('CREATE POLICY "Public select on %I" ON %I FOR SELECT USING (true);', tbl, tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Public insert on %I" ON %I;', tbl, tbl);
    EXECUTE format('CREATE POLICY "Public insert on %I" ON %I FOR INSERT WITH CHECK (true);', tbl, tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Public update on %I" ON %I;', tbl, tbl);
    EXECUTE format('CREATE POLICY "Public update on %I" ON %I FOR UPDATE USING (true);', tbl, tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Public delete on %I" ON %I;', tbl, tbl);
    EXECUTE format('CREATE POLICY "Public delete on %I" ON %I FOR DELETE USING (true);', tbl, tbl);
  END LOOP;
END $$;

-- Reload Supabase Schema Cache
NOTIFY pgrst, 'reload schema';
