-- ==============================================================================
-- PLAZA MANAGEMENT SYSTEM - ROBUST INDEPENDENT TABLES SETUP
-- Paste and Run in Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. UNITS TABLE
CREATE TABLE IF NOT EXISTS public.units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT DEFAULT 1,
  unit_number TEXT NOT NULL,
  unit_name TEXT NOT NULL,
  unit_type TEXT NOT NULL DEFAULT 'SHOP',
  floor TEXT NOT NULL DEFAULT 'Ground',
  default_monthly_rent NUMERIC NOT NULL DEFAULT 0,
  default_security_amount NUMERIC NOT NULL DEFAULT 0,
  default_rent_due_day INTEGER NOT NULL DEFAULT 5,
  status TEXT NOT NULL DEFAULT 'VACANT',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TENANTS TABLE
CREATE TABLE IF NOT EXISTS public.tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT DEFAULT 1,
  full_name TEXT NOT NULL,
  phone TEXT,
  cnic TEXT,
  emergency_contact TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. LEASES TABLE
CREATE TABLE IF NOT EXISTS public.leases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT DEFAULT 1,
  tenant_id BIGINT NOT NULL,
  unit_id BIGINT NOT NULL,
  monthly_rent NUMERIC NOT NULL DEFAULT 0,
  rent_due_day INTEGER NOT NULL DEFAULT 5,
  security_amount NUMERIC NOT NULL DEFAULT 0,
  security_paid NUMERIC NOT NULL DEFAULT 0,
  security_status TEXT NOT NULL DEFAULT 'UNPAID',
  move_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  lease_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  lease_end_date DATE,
  annual_increase_pct NUMERIC DEFAULT 10,
  last_escalation_date DATE,
  next_escalation_date DATE,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  ended_at TIMESTAMPTZ,
  vacate_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CONNECTION UNIT MAPPINGS
CREATE TABLE IF NOT EXISTS public.connection_unit_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id BIGINT NOT NULL,
  unit_id BIGINT NOT NULL,
  split_type TEXT NOT NULL DEFAULT 'EQUAL',
  split_value NUMERIC NOT NULL DEFAULT 100,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. MONTHLY TENANT ACCOUNTS
CREATE TABLE IF NOT EXISTS public.tenant_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT DEFAULT 1,
  tenant_id BIGINT NOT NULL,
  lease_id BIGINT,
  unit_id BIGINT NOT NULL,
  billing_month DATE NOT NULL,
  rent_amount NUMERIC NOT NULL DEFAULT 0,
  rent_due_date DATE,
  rent_paid NUMERIC NOT NULL DEFAULT 0,
  rent_status TEXT NOT NULL DEFAULT 'UNPAID',
  electricity_amount NUMERIC DEFAULT NULL,
  electricity_due_date DATE DEFAULT NULL,
  electricity_paid NUMERIC NOT NULL DEFAULT 0,
  electricity_status TEXT NOT NULL DEFAULT 'UNPAID',
  has_electricity_bill BOOLEAN DEFAULT false,
  electricity_is_shared BOOLEAN DEFAULT false,
  maintenance_amount NUMERIC NOT NULL DEFAULT 0,
  other_charges NUMERIC NOT NULL DEFAULT 0,
  previous_balance NUMERIC NOT NULL DEFAULT 0,
  total_payable NUMERIC NOT NULL DEFAULT 0,
  total_paid NUMERIC NOT NULL DEFAULT 0,
  remaining_balance NUMERIC NOT NULL DEFAULT 0,
  overall_status TEXT NOT NULL DEFAULT 'UNPAID',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. COMPLAINTS & REPAIRS
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT DEFAULT 1,
  unit_id BIGINT NOT NULL,
  tenant_id BIGINT,
  complaint_number TEXT NOT NULL,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  photo_attachment TEXT,
  complaint_date DATE NOT NULL DEFAULT CURRENT_DATE,
  priority TEXT NOT NULL DEFAULT 'MEDIUM',
  status TEXT NOT NULL DEFAULT 'OPEN',
  assigned_to TEXT,
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.complaint_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT NOT NULL,
  expense_type TEXT NOT NULL DEFAULT 'MATERIAL',
  description TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  vendor_name TEXT,
  payment_method TEXT DEFAULT 'Cash',
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. GENERAL PLAZA EXPENSES
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT DEFAULT 1,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT NOT NULL DEFAULT 'Cash',
  paid_to TEXT,
  receipt_voucher_no TEXT,
  is_recurring BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. EXTEND PAYMENTS IF NEEDED
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS lease_id BIGINT;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'RENT';

-- 9. ENABLE PUBLIC ACCESS POLICIES
ALTER TABLE public.units DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.connection_unit_mappings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;

-- 10. REFRESH SCHEMA CACHE
NOTIFY pgrst, 'reload schema';
