-- Phase 3: Electricity Connection & Unit Meter Mapping Migration

-- 1. Create connection_unit_mappings table
CREATE TABLE IF NOT EXISTS connection_unit_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id BIGINT REFERENCES connections(id) ON DELETE CASCADE NOT NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  split_type TEXT NOT NULL DEFAULT 'EQUAL' CHECK (split_type IN ('EQUAL', 'PERCENTAGE', 'FIXED_AMOUNT')),
  split_value NUMERIC NOT NULL DEFAULT 100, -- 100 for 100%, 50 for 50%, etc.
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_conn_unit UNIQUE (connection_id, unit_id)
);

-- Indexes for lightning fast lookups
CREATE INDEX IF NOT EXISTS idx_conn_unit_conn_id ON connection_unit_mappings(connection_id);
CREATE INDEX IF NOT EXISTS idx_conn_unit_unit_id ON connection_unit_mappings(unit_id);

-- Enable RLS
ALTER TABLE connection_unit_mappings ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on connection_unit_mappings') THEN
    CREATE POLICY "Allow public select on connection_unit_mappings" ON connection_unit_mappings FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on connection_unit_mappings') THEN
    CREATE POLICY "Allow public insert on connection_unit_mappings" ON connection_unit_mappings FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on connection_unit_mappings') THEN
    CREATE POLICY "Allow public update on connection_unit_mappings" ON connection_unit_mappings FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on connection_unit_mappings') THEN
    CREATE POLICY "Allow public delete on connection_unit_mappings" ON connection_unit_mappings FOR DELETE USING (true);
  END IF;
END $$;
