-- Phase 6: Complaint Management Migration

CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE SET NULL,
  complaint_number TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Electrical', 'Wall / Paint', 'Roof', 'Water / Plumbing', 'Door / Lock', 'Flooring', 'AC', 'Washroom', 'Leakage', 'Structural', 'Other')),
  title TEXT NOT NULL,
  description TEXT,
  photo_attachment TEXT,
  complaint_date DATE NOT NULL DEFAULT CURRENT_DATE,
  priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
  assigned_to TEXT,
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_complaints_unit_id ON complaints(unit_id);
CREATE INDEX IF NOT EXISTS idx_complaints_tenant_id ON complaints(tenant_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_priority ON complaints(priority);
CREATE INDEX IF NOT EXISTS idx_complaints_date ON complaints(complaint_date);

-- Enable RLS
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on complaints') THEN
    CREATE POLICY "Allow public select on complaints" ON complaints FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on complaints') THEN
    CREATE POLICY "Allow public insert on complaints" ON complaints FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on complaints') THEN
    CREATE POLICY "Allow public update on complaints" ON complaints FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on complaints') THEN
    CREATE POLICY "Allow public delete on complaints" ON complaints FOR DELETE USING (true);
  END IF;
END $$;
