-- Phase 4: Enhanced Monthly Tenant Accounts & Ledgers Migration

-- 1. Create enhanced monthly tenant accounts table
CREATE TABLE IF NOT EXISTS tenant_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  lease_id BIGINT REFERENCES leases(id) ON DELETE SET NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  billing_month DATE NOT NULL,
  
  -- Rent details
  rent_amount NUMERIC NOT NULL DEFAULT 0,
  rent_due_date DATE,
  rent_paid NUMERIC NOT NULL DEFAULT 0,
  rent_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (rent_status IN ('PAID', 'PARTIAL', 'UNPAID', 'OVERDUE')),
  
  -- Electricity details (with split support from Phase 3)
  electricity_amount NUMERIC DEFAULT NULL,
  electricity_due_date DATE DEFAULT NULL,
  electricity_paid NUMERIC NOT NULL DEFAULT 0,
  electricity_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (electricity_status IN ('PAID', 'PARTIAL', 'UNPAID', 'OVERDUE')),
  has_electricity_bill BOOLEAN DEFAULT false,
  electricity_is_shared BOOLEAN DEFAULT false,
  
  -- Additional charges & prior balance
  maintenance_amount NUMERIC NOT NULL DEFAULT 0,
  other_charges NUMERIC NOT NULL DEFAULT 0,
  previous_balance NUMERIC NOT NULL DEFAULT 0,
  
  -- Total metrics
  total_payable NUMERIC NOT NULL DEFAULT 0,
  total_paid NUMERIC NOT NULL DEFAULT 0,
  remaining_balance NUMERIC NOT NULL DEFAULT 0,
  overall_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (overall_status IN ('PAID', 'PARTIAL', 'UNPAID', 'OVERDUE')),
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  CONSTRAINT unique_tenant_account_month UNIQUE (tenant_id, billing_month),
  CONSTRAINT unique_unit_account_month UNIQUE (unit_id, billing_month)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tenant_accounts_tenant_id ON tenant_accounts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_accounts_unit_id ON tenant_accounts(unit_id);
CREATE INDEX IF NOT EXISTS idx_tenant_accounts_billing_month ON tenant_accounts(billing_month);
CREATE INDEX IF NOT EXISTS idx_tenant_accounts_overall_status ON tenant_accounts(overall_status);

-- Enable RLS
ALTER TABLE tenant_accounts ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on tenant_accounts') THEN
    CREATE POLICY "Allow public select on tenant_accounts" ON tenant_accounts FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on tenant_accounts') THEN
    CREATE POLICY "Allow public insert on tenant_accounts" ON tenant_accounts FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on tenant_accounts') THEN
    CREATE POLICY "Allow public update on tenant_accounts" ON tenant_accounts FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on tenant_accounts') THEN
    CREATE POLICY "Allow public delete on tenant_accounts" ON tenant_accounts FOR DELETE USING (true);
  END IF;
END $$;
