-- Phase 2: Rent Management + Tenant Monthly Ledgers Migration

-- 1. Extend connections table with rent lease configuration columns
ALTER TABLE connections 
  ADD COLUMN IF NOT EXISTS monthly_rent NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rent_due_day INT DEFAULT 5,
  ADD COLUMN IF NOT EXISTS security_deposit NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lease_start_date DATE,
  ADD COLUMN IF NOT EXISTS lease_end_date DATE,
  ADD COLUMN IF NOT EXISTS annual_increase_pct NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lease_status TEXT DEFAULT 'active';

-- 2. Create tenant_monthly_ledgers table
CREATE TABLE IF NOT EXISTS tenant_monthly_ledgers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id BIGINT REFERENCES connections(id) ON DELETE CASCADE NOT NULL,
  tenant_name TEXT,
  billing_month DATE NOT NULL,
  rent_amount NUMERIC DEFAULT 0 NOT NULL,
  maintenance_amount NUMERIC DEFAULT 0 NOT NULL,
  other_charges NUMERIC DEFAULT 0 NOT NULL,
  paid_amount NUMERIC DEFAULT 0 NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_tenant_month_ledger UNIQUE (connection_id, billing_month)
);

-- 3. RLS Policies
ALTER TABLE connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_monthly_ledgers ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on connections') THEN
    CREATE POLICY "Allow public select on connections" ON connections FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on connections') THEN
    CREATE POLICY "Allow public insert on connections" ON connections FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on connections') THEN
    CREATE POLICY "Allow public update on connections" ON connections FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on ledgers') THEN
    CREATE POLICY "Allow public select on ledgers" ON tenant_monthly_ledgers FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on ledgers') THEN
    CREATE POLICY "Allow public insert on ledgers" ON tenant_monthly_ledgers FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on ledgers') THEN
    CREATE POLICY "Allow public update on ledgers" ON tenant_monthly_ledgers FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on ledgers') THEN
    CREATE POLICY "Allow public delete on ledgers" ON tenant_monthly_ledgers FOR DELETE USING (true);
  END IF;
END $$;
