-- Phase 4: Tenant Notifications Table Migration

CREATE TABLE IF NOT EXISTS tenant_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE,
  lease_id BIGINT REFERENCES leases(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN (
    'RENT_CREATED',
    'RENT_REMINDER',
    'RENT_DUE_TODAY',
    'RENT_OVERDUE',
    'ELECTRICITY_BILL_AVAILABLE',
    'MAINTENANCE_UPDATE',
    'GENERAL'
  )),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  href TEXT,
  read BOOLEAN DEFAULT false,
  dedup_key TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tenant_notifications_tenant_id ON tenant_notifications(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_notifications_read ON tenant_notifications(read);
CREATE INDEX IF NOT EXISTS idx_tenant_notifications_dedup_key ON tenant_notifications(dedup_key);

-- Enable RLS
ALTER TABLE tenant_notifications ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on tenant_notifications') THEN
    CREATE POLICY "Allow public select on tenant_notifications" ON tenant_notifications FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on tenant_notifications') THEN
    CREATE POLICY "Allow public insert on tenant_notifications" ON tenant_notifications FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on tenant_notifications') THEN
    CREATE POLICY "Allow public update on tenant_notifications" ON tenant_notifications FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on tenant_notifications') THEN
    CREATE POLICY "Allow public delete on tenant_notifications" ON tenant_notifications FOR DELETE USING (true);
  END IF;
END $$;
