-- Phase 7: Complaint / Maintenance Expenses Migration

CREATE TABLE IF NOT EXISTS complaint_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE NOT NULL,
  expense_type TEXT NOT NULL DEFAULT 'MATERIAL' CHECK (expense_type IN ('MATERIAL', 'LABOUR', 'OTHER')),
  description TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  vendor_name TEXT,
  payment_method TEXT DEFAULT 'Cash',
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_complaint_expenses_complaint_id ON complaint_expenses(complaint_id);
CREATE INDEX IF NOT EXISTS idx_complaint_expenses_type ON complaint_expenses(expense_type);
CREATE INDEX IF NOT EXISTS idx_complaint_expenses_date ON complaint_expenses(expense_date);

-- Enable RLS
ALTER TABLE complaint_expenses ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on complaint_expenses') THEN
    CREATE POLICY "Allow public select on complaint_expenses" ON complaint_expenses FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on complaint_expenses') THEN
    CREATE POLICY "Allow public insert on complaint_expenses" ON complaint_expenses FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on complaint_expenses') THEN
    CREATE POLICY "Allow public update on complaint_expenses" ON complaint_expenses FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on complaint_expenses') THEN
    CREATE POLICY "Allow public delete on complaint_expenses" ON complaint_expenses FOR DELETE USING (true);
  END IF;
END $$;
