-- Phase 8: General Plaza Expenses Migration

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN (
    'Generator Fuel / Maintenance',
    'Security Guard Salary',
    'Janitorial / Sweeper / Cleaning',
    'Common Area Utilities',
    'Waste Disposal',
    'Government Taxes / Property Tax',
    'Building Maintenance / Repairs',
    'Legal / Admin',
    'Other'
  )),
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT NOT NULL DEFAULT 'Cash' CHECK (payment_method IN ('Cash', 'Bank Transfer', 'Online', 'Cheque', 'Other')),
  paid_to TEXT,
  receipt_voucher_no TEXT,
  is_recurring BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for lightning fast analytics
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_expenses_plaza_id ON expenses(plaza_id);

-- Enable RLS
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on expenses') THEN
    CREATE POLICY "Allow public select on expenses" ON expenses FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on expenses') THEN
    CREATE POLICY "Allow public insert on expenses" ON expenses FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on expenses') THEN
    CREATE POLICY "Allow public update on expenses" ON expenses FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on expenses') THEN
    CREATE POLICY "Allow public delete on expenses" ON expenses FOR DELETE USING (true);
  END IF;
END $$;
