-- Phase 2: Tenant & Lease Management Migration

-- 1. Create tenants table
CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT,
  cnic TEXT,
  emergency_contact TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'VACATED', 'INACTIVE')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create leases table (Tenant -> Unit occupancy relationship)
CREATE TABLE IF NOT EXISTS leases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE NOT NULL,
  monthly_rent NUMERIC NOT NULL DEFAULT 0,
  rent_due_day INT NOT NULL DEFAULT 5,
  security_amount NUMERIC NOT NULL DEFAULT 0,
  security_paid NUMERIC NOT NULL DEFAULT 0,
  security_status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (security_status IN ('PAID', 'PARTIAL', 'UNPAID')),
  move_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  lease_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  lease_end_date DATE,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ENDED', 'TERMINATED')),
  ended_at TIMESTAMPTZ,
  vacate_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);
CREATE INDEX IF NOT EXISTS idx_leases_tenant_id ON leases(tenant_id);
CREATE INDEX IF NOT EXISTS idx_leases_unit_id ON leases(unit_id);
CREATE INDEX IF NOT EXISTS idx_leases_status ON leases(status);

-- Enable RLS
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE leases ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on tenants') THEN
    CREATE POLICY "Allow public select on tenants" ON tenants FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on tenants') THEN
    CREATE POLICY "Allow public insert on tenants" ON tenants FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on tenants') THEN
    CREATE POLICY "Allow public update on tenants" ON tenants FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on tenants') THEN
    CREATE POLICY "Allow public delete on tenants" ON tenants FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on leases') THEN
    CREATE POLICY "Allow public select on leases" ON leases FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on leases') THEN
    CREATE POLICY "Allow public insert on leases" ON leases FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on leases') THEN
    CREATE POLICY "Allow public update on leases" ON leases FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on leases') THEN
    CREATE POLICY "Allow public delete on leases" ON leases FOR DELETE USING (true);
  END IF;
END $$;
