-- Phase 3: Proper Payment & Receipt System Migration

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ledger_id BIGINT REFERENCES tenant_monthly_ledgers(id) ON DELETE CASCADE,
  connection_id BIGINT REFERENCES connections(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT NOT NULL DEFAULT 'Cash', -- 'Cash', 'Bank Transfer', 'Cheque', 'Online', 'Other'
  transaction_reference TEXT,
  receipt_number TEXT UNIQUE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_payments_ledger_id ON payments(ledger_id);
CREATE INDEX IF NOT EXISTS idx_payments_connection_id ON payments(connection_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON payments(payment_date);

-- Enable RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on payments') THEN
    CREATE POLICY "Allow public select on payments" ON payments FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on payments') THEN
    CREATE POLICY "Allow public insert on payments" ON payments FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on payments') THEN
    CREATE POLICY "Allow public update on payments" ON payments FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on payments') THEN
    CREATE POLICY "Allow public delete on payments" ON payments FOR DELETE USING (true);
  END IF;
END $$;
