-- Phase 1: Plaza & Unit Structure Migration

-- 1. Create plazas table
CREATE TABLE IF NOT EXISTS plazas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  description TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure default plaza exists
INSERT INTO plazas (name, address, description)
SELECT 'Main Commercial Plaza', 'Commercial Center', 'Multi-story commercial plaza with shops and flat rooms'
WHERE NOT EXISTS (SELECT 1 FROM plazas);

-- 2. Create units table (Permanent rentable shops and rooms)
CREATE TABLE IF NOT EXISTS units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plaza_id BIGINT REFERENCES plazas(id) ON DELETE CASCADE NOT NULL,
  unit_number TEXT NOT NULL,
  unit_name TEXT NOT NULL,
  unit_type TEXT NOT NULL DEFAULT 'SHOP' CHECK (unit_type IN ('SHOP', 'ROOM', 'OTHER')),
  floor TEXT NOT NULL DEFAULT 'Ground',
  default_monthly_rent NUMERIC NOT NULL DEFAULT 0,
  default_security_amount NUMERIC NOT NULL DEFAULT 0,
  default_rent_due_day INT NOT NULL DEFAULT 5,
  status TEXT NOT NULL DEFAULT 'VACANT' CHECK (status IN ('OCCUPIED', 'VACANT', 'INACTIVE')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_unit_in_plaza UNIQUE (plaza_id, unit_number)
);

-- 3. Indexes for fast filtering
CREATE INDEX IF NOT EXISTS idx_units_plaza_id ON units(plaza_id);
CREATE INDEX IF NOT EXISTS idx_units_type ON units(unit_type);
CREATE INDEX IF NOT EXISTS idx_units_status ON units(status);

-- 4. Add unit_id to connections table (backward-compatible reference)
ALTER TABLE connections ADD COLUMN IF NOT EXISTS unit_id BIGINT REFERENCES units(id) ON DELETE SET NULL;

-- 5. Enable RLS
ALTER TABLE plazas ENABLE ROW LEVEL SECURITY;
ALTER TABLE units ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on plazas') THEN
    CREATE POLICY "Allow public select on plazas" ON plazas FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on plazas') THEN
    CREATE POLICY "Allow public insert on plazas" ON plazas FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on plazas') THEN
    CREATE POLICY "Allow public update on plazas" ON plazas FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on units') THEN
    CREATE POLICY "Allow public select on units" ON units FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on units') THEN
    CREATE POLICY "Allow public insert on units" ON units FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on units') THEN
    CREATE POLICY "Allow public update on units" ON units FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on units') THEN
    CREATE POLICY "Allow public delete on units" ON units FOR DELETE USING (true);
  END IF;
END $$;
